<?php

/**
 * @file
 * Contains cars.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cars_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cars module.
    case 'help.page.cars':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cars module') . '</p>';
      return $output;

    default:
  }
}

function cars_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == 'comment_comment_form') {
    $form['actions']['submit']['#value'] = t('Comment');
  }
}